name: flutter_form_bloc
description: Create Beautiful Forms in Flutter. The easiest way to Prefill, Async Validation, Update Form Fields, and Show Progress, Failures or Navigate by Reacting to the Form State.
version: 0.20.0
homepage: https://github.com/GiancarloCode/form_bloc/tree/master/packages/flutter_form_bloc
repository: https://github.com/GiancarloCode/form_bloc/tree/master/packages/flutter_form_bloc
issue_tracker: https://github.com/GiancarloCode/form_bloc/issues

environment:
  sdk: '>=2.6.0 <3.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_bloc: ^7.0.0
#  form_bloc: ^0.19.1
#  form_bloc:
#    path: ../form_bloc
  form_bloc:
    git:
      url: https://github.com/aaassseee/form_bloc.git
      ref: temp
      path: packages/form_bloc
  flutter_keyboard_visibility: ^5.0.1
  collection: ^1.15.0-nullsafety.5
  intl: ^0.17.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  pedantic: ^1.9.2
