name: form_bloc
description: 'Easy Form State Management using BLoC pattern. Separate the Form State and Business Logic from the User Interface. Async Validation, Progress, Dynamic fields, and more.'
version: 0.30.1
homepage: 'https://github.com/GiancarloCode/form_bloc/tree/master/packages/form_bloc'
repository: 'https://github.com/GiancarloCode/form_bloc/tree/master/packages/form_bloc'
issue_tracker: 'https://github.com/GiancarloCode/form_bloc/issues'

environment:
  sdk: '>=2.14.0 <3.0.0'

dependencies:
  meta: ^1.8.0
  bloc: ^8.1.0
  rxdart: ^0.27.5
  equatable: ^2.0.5
  collection: ^1.16.0
  uuid: ^3.0.6

dev_dependencies:
  test: ^1.21.6
  mocktail: ^0.3.0
  bloc_test: ^9.1.0
  fire_line_diff: ^1.5.5

  lints: ^2.0.0
