name: form_bloc
description: Easy Form State Management using BLoC pattern. Separate the Form State and Business Logic from the User Interface. Async Validation, Progress, Dynamic fields, and more.
version: 0.19.7
homepage: https://github.com/GiancarloCode/form_bloc/tree/master/packages/form_bloc
repository: https://github.com/GiancarloCode/form_bloc/tree/master/packages/form_bloc
issue_tracker: https://github.com/GiancarloCode/form_bloc/issues

environment:
  sdk: '>=2.6.0 <3.0.0'

dependencies:
  meta: ^1.3.0-nullsafety.6
  bloc: ^7.0.0-nullsafety.3
  bloc_test: ^8.0.0-nullsafety.1
  rxdart: ^0.25.0
  equatable: ^2.0.0
  quiver: ^2.1.5
  mockito: ^4.1.4
  pedantic: ^1.10.0-nullsafety.3
  collection: ^1.15.0-nullsafety.5
  uuid: ^3.0.0

dev_dependencies:
  test: ^1.6.0
